export const familyMembersList = [
    { english: "Father", spanish: "Padre" },
    { english: "Mother", spanish: "Madre" },
    { english: "Brother", spanish: "Hermano" },
    { english: "Sister", spanish: "Hermana" },
    { english: "Grandfather", spanish: "Abuelo" },
    { english: "Grandmother", spanish: "Abuela" },
    { english: "Uncle", spanish: "Tío" },
    { english: "Aunt", spanish: "Tía" },
    { english: "Cousin", spanish: "Primo" },
    { english: "Son", spanish: "Hijo" },
    { english: "Daughter", spanish: "Hija" },
    { english: "Nephew", spanish: "Sobrino" },
    { english: "Niece", spanish: "Sobrina" },
    { english: "Husband", spanish: "Esposo" },
    { english: "Wife", spanish: "Esposa" },
    { english: "Stepfather", spanish: "Padrastro" },
    { english: "Stepmother", spanish: "Madrastra" },
    { english: "Stepbrother", spanish: "Hermanastro" },
    { english: "Stepsister", spanish: "Hermanastra" },
    { english: "Father in law", spanish: "Suegro" },
    { english: "Mother in law", spanish: "Suegra" },
    { english: "Brother in law", spanish: "Cuñado" },
    { english: "Sister in law", spanish: "Cuñada" }
];