export const fruitsList = [
    { english: "Apple", spanish: "Manzana" },
    { english: "Banana", spanish: "Plátano" },
    { english: "Orange", spanish: "Naranja" },
    { english: "Strawberry", spanish: "Fresa" },
    { english: "Grape", spanish: "Uva" },
    { english: "Pineapple", spanish: "Piña" },
    { english: "Watermelon", spanish: "Sandía" },
    { english: "Mango", spanish: "Mango" },
    { english: "Blueberry", spanish: "Arándano" },
    { english: "Cherry", spanish: "Cereza" },
    { english: "Peach", spanish: "Durazno" },
    { english: "Pear", spanish: "Pera" },
    { english: "Kiwi", spanish: "Kiwi" },
    { english: "Lemon", spanish: "Limón" },
    { english: "Coconut", spanish: "Coco" },
    { english: "Papaya", spanish: "Papaya" },
    { english: "Plum", spanish: "Ciruela" },
    { english: "Raspberry", spanish: "Frambuesa" },
    { english: "Blackberry", spanish: "Mora" },
    { english: "Pomegranate", spanish: "Granada" },
    { english: "Fig", spanish: "Higo" },
    { english: "Avocado", spanish: "Aguacate" },
    { english: "Guava", spanish: "Guayaba" },
    { english: "Melon", spanish: "Melón" },
    { english: "Lychee", spanish: "Lichis" },
    { english: "Apricot", spanish: "Albaricoque" },
    { english: "Mandarin", spanish: "Mandarina" },
    { english: "Passion Fruit", spanish: "Maracuyá" },
    { english: "Lime", spanish: "Lima" }
];